name: CICD

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Node setup
        uses: actions/setup-node@v7

      - name: Install project dependencies
        run: npm install

      - name: Run tests
        run: npm run check

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Install project dependencies
        run: npm install

      - name: Deploy
        run: pm2 start "npm restart" --name="CICD 5000"