name: CICD

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Node setup
        uses: actions/setup-node@v7

      - name: Install project dependencies
        run: npm install

      - name: Run tests
        run: npm run check

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: File create
        run: echo "Hello World" > file.txt

      - name: Output the file
        run: cat file.txt
      # - name: Clone repository
      #   uses: actions/checkout@v2

      # - name: Install project dependencies
      #   run: npm install

      # - name: Deploy
      #   run: pm2 start "npm start" --name="CICD 5000"