name: CICD

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Node setup
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Install project dependencies
        run: npm install

      - name: Run tests
        run: npm run check > test_result.txt

      - name: Upload artifacts
        uses: gaogaotiantian/upload-coredumpy@v0.2
        with:
          name: test_result
          path: test_results
          

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Install project dependencies
        run: npm install

      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: test_result
          path: test_results

      - name: Show artifacts
        run: cat test_results/test_result.txt

      - name: Deploy
        run: pm2 restart "CICD 5000" || pm2 start "npm start" --name="CICD 5000"